server:
  port: 7500

spring:
  profiles:
    active: dev
  application:
    name: gateway-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 指定druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: admini
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          ## 开启从注册中心动态创建路由的功能，利用服务名进行路由，默认false
#          enabled: true
#      ### 路由
#      routes:
#        ### 路由的ID
#        - id: generator-center
#            ### 匹配路由的转发地址
#          uri: http://127.0.0.1:8001/
#          # uri: lb://generator-center/
#          predicates:
#            ### 匹配路径转发
#            - Path=/generator/**

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xh.**.model.**.*