server:
  port: 7500

spring:
  profiles:
    active: dev
  application:
    name: gateway-center
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          ## 开启从注册中心动态创建路由的功能，利用服务名进行路由，默认false
#          enabled: true
      ### 路由
      routes:
        ### 路由的ID
        - id: generator-center
            ### 匹配路由的转发地址
          uri: http://127.0.0.1:8001/
          # uri: lb://generator-center/
          predicates:
            ### 匹配路径转发
            - Path=/generator/**

knife4j:
  swagger:
    enabled: true
    knife4j-type: cloud